# Generated by Django 4.1.5 on 2023-07-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinterest',
            options={'verbose_name': 'User interest'},
        ),
    ]
