# Generated by Django 4.2.3 on 2023-07-23 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
        ('hashtag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='complainant_id',
            field=models.ForeignKey(db_column='complainant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complainant_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='defendant_id',
            field=models.ForeignKey(db_column='defendant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defendant_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reason_id',
            field=models.ForeignKey(db_column='reason_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_set', to='board.reportreason'),
        ),
        migrations.AddField(
            model_name='post',
            name='board_id',
            field=models.ForeignKey(blank=True, db_column='board_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_set', to='board.board', verbose_name='board category'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtag_id',
            field=models.ForeignKey(blank=True, db_column='hashtag_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_set', to='hashtag.hashtag', verbose_name='subTopic'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_set', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likepostassoc',
            name='post_id',
            field=models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_post_assoc_set', to='board.post'),
        ),
        migrations.AddField(
            model_name='likepostassoc',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_post_assoc_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likecommentassoc',
            name='comment_id',
            field=models.ForeignKey(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_comment_assoc_set', to='board.comment'),
        ),
        migrations.AddField(
            model_name='likecommentassoc',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_comment_assoc_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment_id',
            field=models.OneToOneField(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_comment', to='board.comment', verbose_name='parent comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(blank=True, db_column='post_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_set', to='board.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardhashtagassoc',
            name='board_id',
            field=models.ForeignKey(blank=True, db_column='board_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hashtag_assoc_set', to='board.board', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='boardhashtagassoc',
            name='hashtag_id',
            field=models.ForeignKey(blank=True, db_column='hashtag_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_assoc_set', to='hashtag.hashtag', verbose_name='topic'),
        ),
    ]
