# Generated by Django 4.1.5 on 2023-07-24 11:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hashtag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('view', models.PositiveIntegerField(default=0)),
                ('like', models.PositiveIntegerField(default=0)),
                ('report', models.PositiveIntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
                ('reserve_at', models.DateTimeField(blank=True, null=True)),
                ('hashtag_id', models.ForeignKey(blank=True, db_column='hashtag_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magazine_set', to='hashtag.hashtag', verbose_name='magazine')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magazine_set', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
