# Generated by Django 4.1.5 on 2023-07-24 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbticlass',
            name='mbti',
            field=models.CharField(choices=[('ESFJ', 'ESFJ'), ('ESTJ', 'ESTJ'), ('ESFP', 'ESFP'), ('ESTP', 'ESTP'), ('ISFJ', 'ISFJ'), ('ISTJ', 'ISTJ'), ('ISFP', 'ISFP'), ('ISTP', 'ISTP'), ('ENFJ', 'ENFJ'), ('ENTJ', 'ENTJ'), ('ENFP', 'ENFP'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('INTJ', 'INTJ'), ('INFP', 'INFP'), ('INTP', 'INTP'), ('XXXX', 'XXXX')], max_length=4, validators=[django.core.validators.RegexValidator(message='Not match MBTI Characters', regex='[IEX][SNX][TFX][PJX]')]),
        ),
    ]
